# Generated by Django 5.2.8 on 2025-11-27 14:16

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transcript',
            fields=[
                ('transcript_id', models.CharField(default=uuid.uuid4, max_length=100, primary_key=True, serialize=False, unique=True)),
                ('transcript_text', models.TextField()),
                ('source_lan', models.TextField(default='en')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'transcripts',
                'get_latest_by': 'created_at',
            },
        ),
    ]
