# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: media.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'media.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bmedia.proto\x12\x05media\"\"\n\x0cVideoRequest\x12\x12\n\nvideo_data\x18\x01 \x01(\x0c\"#\n\rAudioResponse\x12\x12\n\naudio_data\x18\x01 \x01(\x0c\x32I\n\x0cMediaService\x12\x39\n\x0c\x45xtractAudio\x12\x13.media.VideoRequest\x1a\x14.media.AudioResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'media_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_VIDEOREQUEST']._serialized_start=22
  _globals['_VIDEOREQUEST']._serialized_end=56
  _globals['_AUDIORESPONSE']._serialized_start=58
  _globals['_AUDIORESPONSE']._serialized_end=93
  _globals['_MEDIASERVICE']._serialized_start=95
  _globals['_MEDIASERVICE']._serialized_end=168
# @@protoc_insertion_point(module_scope)
