# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: media.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'media.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bmedia.proto\x12\x05media\"\x07\n\x05\x45mpty\"\x1a\n\nVideoChunk\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\"#\n\rAudioResponse\x12\x12\n\naudio_data\x18\x01 \x01(\x0c\"\x1e\n\x0cHealthStatus\x12\x0e\n\x06status\x18\x01 \x01(\t2{\n\x0cMediaService\x12\x39\n\x0c\x45xtractAudio\x12\x11.media.VideoChunk\x1a\x14.media.AudioResponse(\x01\x12\x30\n\x0bHealthCheck\x12\x0c.media.Empty\x1a\x13.media.HealthStatusb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'media_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMPTY']._serialized_start=22
  _globals['_EMPTY']._serialized_end=29
  _globals['_VIDEOCHUNK']._serialized_start=31
  _globals['_VIDEOCHUNK']._serialized_end=57
  _globals['_AUDIORESPONSE']._serialized_start=59
  _globals['_AUDIORESPONSE']._serialized_end=94
  _globals['_HEALTHSTATUS']._serialized_start=96
  _globals['_HEALTHSTATUS']._serialized_end=126
  _globals['_MEDIASERVICE']._serialized_start=128
  _globals['_MEDIASERVICE']._serialized_end=251
# @@protoc_insertion_point(module_scope)
